Migrate langnames.json
Bible-Translation-Tools/BTT-Writer-Android pull request #79
Opened 2023-07-12 21:45 UTC by AnonymousWalker

We integrated [door43-client v0.10.3](https://github.com/unfoldingWord-dev/android-door43-client) library into Writer Android as the catalog url of `langnames.json` was not configurable in the library above. We need to make change to that endpoint by keeping the source code local to our repo.

2023-07-13 18:10 UTC, PurpleGuitar requested changes

2023-07-14 19:01 UTC, AnonymousWalker commented on app/src/main/java/org/unfoldingword/door43client/LegacyTools.java
> +        library.addCatalog(new Catalog("langnames", "https://langnames-temp.walink.org/langnames.json", 0));
Thanks for the suggestion! I added the configuration field in settings. The field is updated when:
- user manually changes the url and saves it
- user switches content server (e.g. WACS to DCS)
- the app is launched

2023-07-18 15:31 UTC, PurpleGuitar approved these changes

2023-07-26 13:57 UTC, mXaln commented
> We integrated [door43-client v0.10.3](https://github.com/unfoldingWord-dev/android-door43-client) library into Writer Android as the catalog URL of `langnames.json` was not configurable in the library above. We change the endpoint and keep the library source code local in our repo.
> 
> This also adds a fix to the `truncateTable()` method in `org/unfoldingword/door43client/Library.java` which did not clear the table when executed inside a transaction. See [4938a71](https://github.com/Bible-Translation-Tools/BTT-Writer-Android/commit/4938a7189eb3d559c36b448893306afc5477b58d)

Could we fork this library, update it and then load it in gradle?

2023-07-26 14:10 UTC, AnonymousWalker commented
> > We integrated [door43-client v0.10.3](https://github.com/unfoldingWord-dev/android-door43-client) library into Writer Android as the catalog URL of `langnames.json` was not configurable in the library above. We change the endpoint and keep the library source code local in our repo.
> > This also adds a fix to the `truncateTable()` method in `org/unfoldingword/door43client/Library.java` which did not clear the table when executed inside a transaction. See [4938a71](https://github.com/Bible-Translation-Tools/BTT-Writer-Android/commit/4938a7189eb3d559c36b448893306afc5477b58d)
> 
> Could we fork this library, update it and then load it in gradle?

We could. However, this library was built with an outdated version of gradle and some of the dependencies required to build it were no longer available when I attempted to. Furthermore, the library repo appears to be no longer in development for years, which means we just fork and maintain it ourselves. I believe this is why we decided to merge it into BTT Writer Android code base for better maintenance.

2023-07-26 14:23 UTC, mXaln commented
> > > We integrated [door43-client v0.10.3](https://github.com/unfoldingWord-dev/android-door43-client) library into Writer Android as the catalog URL of `langnames.json` was not configurable in the library above. We change the endpoint and keep the library source code local in our repo.
> > > This also adds a fix to the `truncateTable()` method in `org/unfoldingword/door43client/Library.java` which did not clear the table when executed inside a transaction. See [4938a71](https://github.com/Bible-Translation-Tools/BTT-Writer-Android/commit/4938a7189eb3d559c36b448893306afc5477b58d)
> > 
> > 
> > Could we fork this library, update it and then load it in gradle?
> 
> We could. However, this library was built with an outdated version of gradle and some of the dependencies required to build it were no longer available when I attempted to. Furthermore, the library repo appears to be no longer in development for years, which means we have to fork and maintain it ourselves. I believe this is why we decided to merge it into BTT Writer Android code base for better maintenance.

All right then

2023-07-26 14:23 UTC, mXaln approved these changes

2023-07-31 17:12 UTC, merged